### ISSUE TITLE
Move team photos from assets/images to images

### ISSUE THREAD

**Issue by paolap** [coecms/cms-wiki#15]
apologies @greensh16 in my haste to get back to one pull request I forgot about my own comment on your pull request and merged:

* move the images to the images folder from asset/images
*  remove asset/images folder
*  add images as 

![image-caption/name](../images/image.jpg)

and the path where the image is located respect to the file you are adding it too, you can also do more fancy stuff see: https://jupyterbook.org/en/stable/search.html?q=images

**Comment by greensh16** [comment]
@paolap I've probably missed something but where is the images folder located in the repo? or do I need to create it?

**Comment by paolap** [comment]
apologies, again getting confused today!!, anyway we can leave "images" under "assets", if we think there might be another category of assets, otherwise might be better to have just one directory level to make it easier to refer to them.
