### ISSUE TITLE
dropdown and tab bars

### ISSUE THREAD

**Issue by greensh16** [coecms/cms-wiki#22]
All my dropdown and tab sections don't seem to be showing/working on the wiki, even though they were working fine when they were first merged into the repo.

They work fine on my local build of the wiki, the only difference there is that I'm using the up-to-date versions of Jupyter-book (latest is 0.13.1) and jinja2. So I have a feeling that those packages might need to be updated on the wiki.

**Comment by paolap** [comment]
There was an issue with jupyter books and the latest ninja so it is pinned, I can see that on my laptop (where the tabs were working jinja2 is a newer version 3.1.2. I'll check why we had to pin jinja2 as that bug might be resolved and then I'll update the requirements file

**Comment by paolap** [comment]
Looks like it was an issue with sphinx that was importing jinja2 in a way that broke with version above 3.0.0. I think this is fixed and as you and myself found out everything builds fine on our laptop with those more recent versions. So I will remove the pin directly in main and see what happens

**Comment by greensh16** [comment]
So I guess that's why Jinja2 was pinned....

**Comment by paolap** [comment]
It failed because of this requirements in on elf the other packages:
Collecting sphinx<4,>=2
[64](https://github.com/coecms/cms-wiki/actions/runs/3691869218/jobs/6250249989#step:4:65)
  Downloading Sphinx-3.5.4-py3-none-any.whl (2.8 MB)
I think the pin on Jupyter-book should be removed too

**Comment by paolap** [comment]
It is an issue for the sphinx<4 I'm not sure why we have Jupyter-book pinned to 0.11 I honestly think there's no reason for that, mine is 0.13 and I have sphinx 4.5.0. So I'll have another go :-)

**Comment by paolap** [comment]
This worked, I can see your tabs now
